### PR TITLE
[WORDPRESS-28] Use the category of the first product to be used as te…

### PR DESCRIPTION
**Pull request by Arturo777**
**How to test?**

Go to any category from the category links and go to articles, you will see the related posts using the category as terms.
If you want to see the exact terms used for you can open the console and search for `terms::`

[Workspace to test](https://usapps2--eriksbikeshop.myvtex.com/)

### CODE REVIEW

**Review by polishq — CHANGES_REQUESTED** [review]
I'd consider this a breaking change in regards to the intended usage of this component. 

The intended usage (as seen on Worldwide Golf, for example) is that when the user searches for a specific string, the component returns blog search results in addition to the normal product search results. 

We need to keep this behavior intact. Your solution here is good but it needs to be conditional. Can you find a way to only use this behavior if the user is currently on a category page?

**Comment by Arturo777** [comment]
> I'd consider this a breaking change in regards to the intended usage of this component.
> 
> The intended usage (as seen on Worldwide Golf, for example) is that when the user searches for a specific string, the component returns blog search results _for that search term_ in addition to the normal product search results.
> 
> We need to keep this behavior intact. Your solution here is good but it needs to be conditional. Can you find a way to only use this behavior if the user is currently on a category page?

Yes, i will update the PR to keep this behavior intact, in addition i will fix some other bugs i encountered in my way...

**Comment by polishq** [comment]
> I understand what you say, but only when you search for a post using the search bar for articles (not the wordpress search bar), the wordpress app was using the title tag at first instance, this PR change is only to replace this terms when the user uses the generic search-bar for the store (to search for articles).
> 
> If you use the wordpress search you will see that the terms are exactly the same as what you write on the wordpress search component.
> 
> I hope I have explained myself well.

This is the behavior we need to preserve: https://www.worldwidegolfshops.com/ben%20hogan?_q=ben%20hogan&map=ft

Note that this is a product search for "ben hogan", and the user can click the Product/Articles tab to switch between product search results and blog search results

**Comment by Arturo777** [comment]
> > I understand what you say, but only when you search for a post using the search bar for articles (not the wordpress search bar), the wordpress app was using the title tag at first instance, this PR change is only to replace this terms when the user uses the generic search-bar for the store (to search for articles).
> > If you use the wordpress search you will see that the terms are exactly the same as what you write on the wordpress search component.
> > I hope I have explained myself well.
> 
> This is the behavior we need to preserve: https://www.worldwidegolfshops.com/ben%20hogan?_q=ben%20hogan&map=ft
> 
> Note that this is a product search for "ben hogan", and the user can click the Product/Articles tab to switch between product search results and blog search results

I got it, the current app was taking those search terms from the title tag, that's why the behaviour has changed, but now i take the search terms from the params for example in the next url 
(https://usapps2--eriksbikeshop.myvtex.com/snowboard%20bindings?_q=snowboard%20bindings&map=ft) 
I will take `snowboard%20bindings` and in the case there is no params terms like category cases (https://usapps2--eriksbikeshop.myvtex.com/winter/snowboard-bindings/for-whom_Mens) i will take the category of the first product to create the terms, like the main idea of this PR.

**Review by polishq — APPROVED** [review]

**Review by albertm805 — APPROVED** [review]
LGTM

**Pull request merged**
